#!/usr/bin/env python3.7

import boto3
from datetime import timedelta, datetime

today = datetime.now()
begin = today - timedelta(30)

client = boto3.client('ce')

client.get_cost_and_usage(
    TimePeriod={
         'Start': begin.strftime("%Y-%m-%d"),
         'End': today.strftime("%Y-%m-%d")
    },
    Granularity='DAILY',
    Filter={
         },
    Metrics=[
        ],
    GroupBy=[
        {
        },
    ],
    NextPageToken='string' 
)
